/**
 *
 * $Id$
 */
package fr.inria.diverse.pdedependencies2dot.model.validation;

import fr.inria.diverse.pdedependencies2dot.model.Feature;
import fr.inria.diverse.pdedependencies2dot.model.PDEGraph;
import fr.inria.diverse.pdedependencies2dot.model.Plugin;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link fr.inria.diverse.pdedependencies2dot.model.Feature}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FeatureValidator {
	boolean validate();

	boolean validateRequiredFeatures(EList<Feature> value);
	boolean validateContainingGraph(PDEGraph value);
	boolean validateAdditionnalPlugins(EList<Plugin> value);
	boolean validateRequiredPlugins(EList<Plugin> value);
}
