/**
 *
 * $Id$
 */
package fr.inria.diverse.pdedependencies2dot.model.validation;

import fr.inria.diverse.pdedependencies2dot.model.Bundle;
import fr.inria.diverse.pdedependencies2dot.model.Plugin;
import fr.inria.diverse.pdedependencies2dot.model.PluginContainer;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link fr.inria.diverse.pdedependencies2dot.model.Plugin}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PluginValidator {
	boolean validate();

	boolean validateContainingElement(PluginContainer value);
	boolean validateExportedBundles(EList<Bundle> value);
	boolean validateRequiredBundles(EList<Bundle> value);
	boolean validateImportedPackages(EList<Plugin> value);
	boolean validateParameters(String value);
}
