/**
 *
 * $Id$
 */
package fr.inria.diverse.pdedependencies2dot.model.validation;

import fr.inria.diverse.pdedependencies2dot.model.Bundle;
import fr.inria.diverse.pdedependencies2dot.model.Plugin;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link fr.inria.diverse.pdedependencies2dot.model.PluginContainer}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PluginContainerValidator {
	boolean validate();

	boolean validatePlugins(EList<Plugin> value);
	boolean validateHue(float value);
	boolean validateBundles(EList<Bundle> value);
	boolean validateDescription(String value);
}
